//------------------------------------------------------------------------------
// <auto-generated>
//     Simplified input actions wrapper generated for dual player control schemes.
//     Manual edits will be preserved.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }

    private readonly InputActionMap m_PlayerOne;
    private readonly InputAction m_PlayerOne_Move;
    private readonly InputAction m_PlayerOne_Jump;
    private readonly InputAction m_PlayerOne_Kick;

    private readonly InputActionMap m_PlayerTwo;
    private readonly InputAction m_PlayerTwo_Move;
    private readonly InputAction m_PlayerTwo_Jump;
    private readonly InputAction m_PlayerTwo_Kick;

    private int m_KeyboardMouseSchemeIndex = -1;
    private int m_GamepadSchemeIndex = -1;

    public InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    \"name\": \"InputSystem_Actions\",
    \"maps\": [
        {
            \"name\": \"PlayerOne\",
            \"id\": \"eac0f231-22b5-4d02-94d3-3f039bb7d1e8\",
            \"actions\": [
                {
                    \"name\": \"Move\",
                    \"type\": \"Value\",
                    \"id\": \"e42f3d5e-d266-4a09-9a94-333b8c8bd8ec\",
                    \"expectedControlType\": \"Vector2\",
                    \"processors\": \"\",
                    \"interactions\": \"\",
                    \"initialStateCheck\": true
                },
                {
                    \"name\": \"Jump\",
                    \"type\": \"Button\",
                    \"id\": \"0b50b6c9-3ea1-43de-bc4f-201fd94a6f70\",
                    \"expectedControlType\": \"Button\",
                    \"processors\": \"\",
                    \"interactions\": \"\",
                    \"initialStateCheck\": false
                },
                {
                    \"name\": \"Kick\",
                    \"type\": \"Button\",
                    \"id\": \"5cf1df01-e4c5-4673-b523-50670b6250b2\",
                    \"expectedControlType\": \"Button\",
                    \"processors\": \"\",
                    \"interactions\": \"\",
                    \"initialStateCheck\": false
                }
            ],
            \"bindings\": [
                {
                    \"name\": \"Movement\",
                    \"id\": \"e5f61f6f-49aa-4da5-92ce-0f37adc0469a\",
                    \"path\": \"2DVector\",
                    \"interactions\": \"\",
                    \"processors\": \"\",
                    \"groups\": \"\",
                    \"action\": \"Move\",
                    \"isComposite\": true,
                    \"isPartOfComposite\": false
                },
                {
                    \"name\": \"Up\",
                    \"id\": \"d7a4a8e7-08ac-4b46-992d-62975fb0f6d4\",
                    \"path\": \"<Keyboard>/w\",
                    \"interactions\": \"\",
                    \"processors\": \"\",
                    \"groups\": \"Keyboard&Mouse\",
                    \"action\": \"Move\",
                    \"isComposite\": false,
                    \"isPartOfComposite\": true
                },
                {
                    \"name\": \"Down\",
                    \"id\": \"c83b0ebc-af8e-457c-b360-df41b2bb3a62\",
                    \"path\": \"<Keyboard>/s\",
                    \"interactions\": \"\",
                    \"processors\": \"\",
                    \"groups\": \"Keyboard&Mouse\",
                    \"action\": \"Move\",
                    \"isComposite\": false,
                    \"isPartOfComposite\": true
                },
                {
                    \"name\": \"Left\",
                    \"id\": \"29574c25-3261-4d26-8d7f-c5d24b42efc6\",
                    \"path\": \"<Keyboard>/a\",
                    \"interactions\": \"\",
                    \"processors\": \"\",
                    \"groups\": \"Keyboard&Mouse\",
                    \"action\": \"Move\",
                    \"isComposite\": false,
                    \"isPartOfComposite\": true
                },
                {
                    \"name\": \"Right\",
                    \"id\": \"6fc3a9e4-3c3d-4a56-bdbc-4be400879f8d\",
                    \"path\": \"<Keyboard>/d\",
                    \"interactions\": \"\",
                    \"processors\": \"\",
                    \"groups\": \"Keyboard&Mouse\",
                    \"action\": \"Move\",
                    \"isComposite\": false,
                    \"isPartOfComposite\": true
                },
                {
                    \"name\": \"\",
                    \"id\": \"77271dcd-a4de-4f42-bf12-7d85a37b2b40\",
                    \"path\": \"<Gamepad>/leftStick\",
                    \"interactions\": \"\",
                    \"processors\": \"\",
                    \"groups\": \"Gamepad\",
                    \"action\": \"Move\",
                    \"isComposite\": false,
                    \"isPartOfComposite\": false
                },
                {
                    \"name\": \"\",
                    \"id\": \"ae6a1ce0-3564-4dc5-94a3-eab3ba32f5e4\",
                    \"path\": \"<Keyboard>/space\",
                    \"interactions\": \"\",
                    \"processors\": \"\",
                    \"groups\": \"Keyboard&Mouse\",
                    \"action\": \"Jump\",
                    \"isComposite\": false,
                    \"isPartOfComposite\": false
                },
                {
                    \"name\": \"\",
                    \"id\": \"d0475f5c-19d9-4f51-818e-f9de8bf64f7a\",
                    \"path\": \"<Gamepad>/buttonSouth\",
                    \"interactions\": \"\",
                    \"processors\": \"\",
                    \"groups\": \"Gamepad\",
                    \"action\": \"Jump\",
                    \"isComposite\": false,
                    \"isPartOfComposite\": false
                },
                {
                    \"name\": \"\",
                    \"id\": \"5ca2fc77-5f35-4e38-a9a0-487f9c9735f5\",
                    \"path\": \"<Keyboard>/leftCtrl\",
                    \"interactions\": \"\",
                    \"processors\": \"\",
                    \"groups\": \"Keyboard&Mouse\",
                    \"action\": \"Kick\",
                    \"isComposite\": false,
                    \"isPartOfComposite\": false
                },
                {
                    \"name\": \"\",
                    \"id\": \"d9a8de3d-e781-4828-821a-5b94f0b9fe38\",
                    \"path\": \"<Gamepad>/rightTrigger\",
                    \"interactions\": \"\",
                    \"processors\": \"\",
                    \"groups\": \"Gamepad\",
                    \"action\": \"Kick\",
                    \"isComposite\": false,
                    \"isPartOfComposite\": false
                }
            ]
        },
        {
            \"name\": \"PlayerTwo\",
            \"id\": \"c1f28a63-3041-44e2-bb14-29eb2f81251f\",
            \"actions\": [
                {
                    \"name\": \"Move\",
                    \"type\": \"Value\",
                    \"id\": \"91fb7f9c-13fc-42cb-8bc0-6581dd1433f9\",
                    \"expectedControlType\": \"Vector2\",
                    \"processors\": \"\",
                    \"interactions\": \"\",
                    \"initialStateCheck\": true
                },
                {
                    \"name\": \"Jump\",
                    \"type\": \"Button\",
                    \"id\": \"4bfd0eb5-5e5a-4b59-8f7d-9c5d602013c1\",
                    \"expectedControlType\": \"Button\",
                    \"processors\": \"\",
                    \"interactions\": \"\",
                    \"initialStateCheck\": false
                },
                {
                    \"name\": \"Kick\",
                    \"type\": \"Button\",
                    \"id\": \"f2c62f25-5a20-4d8b-9dc1-4607e1c11327\",
                    \"expectedControlType\": \"Button\",
                    \"processors\": \"\",
                    \"interactions\": \"\",
                    \"initialStateCheck\": false
                }
            ],
            \"bindings\": [
                {
                    \"name\": \"Movement\",
                    \"id\": \"f7b24cc7-2cd9-4c65-a3e8-22f4cd0bf05f\",
                    \"path\": \"2DVector\",
                    \"interactions\": \"\",
                    \"processors\": \"\",
                    \"groups\": \"\",
                    \"action\": \"Move\",
                    \"isComposite\": true,
                    \"isPartOfComposite\": false
                },
                {
                    \"name\": \"Up\",
                    \"id\": \"ef1f8f9c-221c-448f-b264-02f86044dd6f\",
                    \"path\": \"<Keyboard>/upArrow\",
                    \"interactions\": \"\",
                    \"processors\": \"\",
                    \"groups\": \"Keyboard&Mouse\",
                    \"action\": \"Move\",
                    \"isComposite\": false,
                    \"isPartOfComposite\": true
                },
                {
                    \"name\": \"Down\",
                    \"id\": \"70108f3c-04a7-4f18-b1f4-6da0ab9880be\",
                    \"path\": \"<Keyboard>/downArrow\",
                    \"interactions\": \"\",
                    \"processors\": \"\",
                    \"groups\": \"Keyboard&Mouse\",
                    \"action\": \"Move\",
                    \"isComposite\": false,
                    \"isPartOfComposite\": true
                },
                {
                    \"name\": \"Left\",
                    \"id\": \"df6be8b1-5dcd-4c35-8dda-d2c1607ad158\",
                    \"path\": \"<Keyboard>/leftArrow\",
                    \"interactions\": \"\",
                    \"processors\": \"\",
                    \"groups\": \"Keyboard&Mouse\",
                    \"action\": \"Move\",
                    \"isComposite\": false,
                    \"isPartOfComposite\": true
                },
                {
                    \"name\": \"Right\",
                    \"id\": \"08c98961-0afb-481d-87cf-7f724c2d4e4d\",
                    \"path\": \"<Keyboard>/rightArrow\",
                    \"interactions\": \"\",
                    \"processors\": \"\",
                    \"groups\": \"Keyboard&Mouse\",
                    \"action\": \"Move\",
                    \"isComposite\": false,
                    \"isPartOfComposite\": true
                },
                {
                    \"name\": \"\",
                    \"id\": \"1a103357-4f06-45cf-a956-3d560f057e5c\",
                    \"path\": \"<Gamepad>/rightStick\",
                    \"interactions\": \"\",
                    \"processors\": \"\",
                    \"groups\": \"Gamepad\",
                    \"action\": \"Move\",
                    \"isComposite\": false,
                    \"isPartOfComposite\": false
                },
                {
                    \"name\": \"\",
                    \"id\": \"a0fa2e17-26a8-4c4c-af36-b9863348ea17\",
                    \"path\": \"<Keyboard>/enter\",
                    \"interactions\": \"\",
                    \"processors\": \"\",
                    \"groups\": \"Keyboard&Mouse\",
                    \"action\": \"Jump\",
                    \"isComposite\": false,
                    \"isPartOfComposite\": false
                },
                {
                    \"name\": \"\",
                    \"id\": \"c4a8b3d4-414c-4226-b0b1-0a7ff628a6d1\",
                    \"path\": \"<Gamepad>/buttonNorth\",
                    \"interactions\": \"\",
                    \"processors\": \"\",
                    \"groups\": \"Gamepad\",
                    \"action\": \"Jump\",
                    \"isComposite\": false,
                    \"isPartOfComposite\": false
                },
                {
                    \"name\": \"\",
                    \"id\": \"3b41ee95-2af5-4705-9033-1d58e3dcd1a4\",
                    \"path\": \"<Keyboard>/rightCtrl\",
                    \"interactions\": \"\",
                    \"processors\": \"\",
                    \"groups\": \"Keyboard&Mouse\",
                    \"action\": \"Kick\",
                    \"isComposite\": false,
                    \"isPartOfComposite\": false
                },
                {
                    \"name\": \"\",
                    \"id\": \"08b9b8ae-b984-469f-b147-79a4f28d83eb\",
                    \"path\": \"<Gamepad>/rightShoulder\",
                    \"interactions\": \"\",
                    \"processors\": \"\",
                    \"groups\": \"Gamepad\",
                    \"action\": \"Kick\",
                    \"isComposite\": false,
                    \"isPartOfComposite\": false
                }
            ]
        }
    ],
    \"controlSchemes\": [
        {
            \"name\": \"Keyboard&Mouse\",
            \"bindingGroup\": \"Keyboard&Mouse\",
            \"devices\": [
                {
                    \"devicePath\": \"<Keyboard>\",
                    \"isOptional\": false,
                    \"isOR\": false
                },
                {
                    \"devicePath\": \"<Mouse>\",
                    \"isOptional\": true,
                    \"isOR\": false
                }
            ]
        },
        {
            \"name\": \"Gamepad\",
            \"bindingGroup\": \"Gamepad\",
            \"devices\": [
                {
                    \"devicePath\": \"<Gamepad>\",
                    \"isOptional\": false,
                    \"isOR\": false
                }
            ]
        }
    ]
}");

        m_PlayerOne = asset.FindActionMap("PlayerOne", throwIfNotFound: true);
        m_PlayerOne_Move = m_PlayerOne.FindAction("Move", throwIfNotFound: true);
        m_PlayerOne_Jump = m_PlayerOne.FindAction("Jump", throwIfNotFound: true);
        m_PlayerOne_Kick = m_PlayerOne.FindAction("Kick", throwIfNotFound: true);

        m_PlayerTwo = asset.FindActionMap("PlayerTwo", throwIfNotFound: true);
        m_PlayerTwo_Move = m_PlayerTwo.FindAction("Move", throwIfNotFound: true);
        m_PlayerTwo_Jump = m_PlayerTwo.FindAction("Jump", throwIfNotFound: true);
        m_PlayerTwo_Kick = m_PlayerTwo.FindAction("Kick", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public struct PlayerOneActions
    {
        private readonly InputActions m_Wrapper;
        public PlayerOneActions(InputActions wrapper) => m_Wrapper = wrapper;
        public InputAction Move => m_Wrapper.m_PlayerOne_Move;
        public InputAction Jump => m_Wrapper.m_PlayerOne_Jump;
        public InputAction Kick => m_Wrapper.m_PlayerOne_Kick;
        public InputActionMap Get() => m_Wrapper.m_PlayerOne;
        public void Enable() => Get().Enable();
        public void Disable() => Get().Disable();
        public bool enabled => Get().enabled;
    }

    public struct PlayerTwoActions
    {
        private readonly InputActions m_Wrapper;
        public PlayerTwoActions(InputActions wrapper) => m_Wrapper = wrapper;
        public InputAction Move => m_Wrapper.m_PlayerTwo_Move;
        public InputAction Jump => m_Wrapper.m_PlayerTwo_Jump;
        public InputAction Kick => m_Wrapper.m_PlayerTwo_Kick;
        public InputActionMap Get() => m_Wrapper.m_PlayerTwo;
        public void Enable() => Get().Enable();
        public void Disable() => Get().Disable();
        public bool enabled => Get().enabled;
    }

    public PlayerOneActions PlayerOne => new PlayerOneActions(this);
    public PlayerTwoActions PlayerTwo => new PlayerTwoActions(this);

    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1)
            {
                m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            }

            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }

    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1)
            {
                m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            }

            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
}
